language: php
php:
  - '5.5.9'
  - '5.6'
  - '7.0'
env:
  global:
    - APP_ENV=staging
    - APP_DEBUG=false
    - APP_KEY=base64:6uvh+tKXJtyN5TmuJEQpUO4oxWdhhzbyYVr8+monDtM=
    - APP_URL=http://localhost
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

install:
  - composer install --no-interaction
  - touch database/database.sqlite
before_script:
  - php artisan migrate
script: phpunit
cache:
  directories:
    - $HOME/.composer/cache
notifications:
  email: false
